_merge: deep
theme: epv-hugo-theme
params:
  debug:
    productionUrl: https://www.reseauexcellence.fr
  default:
    index:
      search:
        active: true
  image_sizes:
    sections:
      organizations:
        logo:
          tablet: false
          desktop: false